### ISSUE TITLE
Permission Viewer 0.8.6 release had no change to the Module Zip, and therefore is not properly downloadable

### ISSUE THREAD

**Issue by Aeristoka** [Malekal4699/fvtt-module-permission-viewer#12]
https://github.com/League-of-Foundry-Developers/fvtt-module-permission-viewer/commit/6955bcf17db0cce3096bd7eb4ab7c3891ff32c52

![image](https://user-images.githubusercontent.com/7988297/120490534-b62e2700-c375-11eb-80e8-197ab20467c0.png)

**Comment by Malekal4699** [comment]
There you go. Released 0.8.7, now sources match versions as well and generated files.
