### ISSUE TITLE
Icons under Scenes tab are not centered

### ISSUE THREAD

**Issue by ckdragons** [Malekal4699/fvtt-module-permission-viewer#14]
Not sure if this is something that can be fixed. I installed another module called smol-foundry. This allows me to resize the scenes banners under the Scenes tab so they aren't so obnoxious. I found that the icons that show which scenes are shared with players are appearing below the scene, not center like the icons under the other tabs. Using Foundry 0.8.8 on Forge. After playing with the smol-foundry settings, it appears that the icons created with the fvtt-module-permission-viewer are set to a specific spacing from the top of the icon instead of centered vertically.

![image](https://user-images.githubusercontent.com/84493092/125966109-a239a3f4-47e4-482e-87fd-dc0b59436221.png)

**Comment by Malekal4699** [comment]
Ah that's annoying. I'll look into it.

**Comment by Malekal4699** [comment]
Seems to be working fine? I tried chrome and firefox.
![image](https://user-images.githubusercontent.com/78604153/126723535-c513eeaf-5947-4f4a-bdba-dca3c7620aff.png)

**Comment by Malekal4699** [comment]
![image](https://user-images.githubusercontent.com/78604153/126723646-ceb609fa-ffd7-4be0-a1b9-f728e74c015c.png)

**Comment by ckdragons** [comment]
Thank you for looking into it. I'm assuming you tested both taller and shorter screen banners? I didn't test the taller because the point for me to install smol-foundry was keep those banners from taking so much space.

**Comment by Malekal4699** [comment]
Ah. Let me check the small one. 

Ok it does not like smaller. I'll check why

**Comment by Malekal4699** [comment]
Alright, smol did not unset line-height so that part was stuck at the 100. 
I'll update the module and push an update. Please test afterward.

**Comment by ckdragons** [comment]
Awesome, thank you! The new update fixes the issue.
![image](https://user-images.githubusercontent.com/84493092/126732374-d018f4a7-2488-43bc-bbd4-078a74761e8b.png)
