### ISSUE TITLE
journal entry icons for permissions aren't different, and two are not clickable

### ISSUE THREAD

**Issue by jcolson** [Malekal4699/fvtt-module-permission-viewer#16]
<img width="220" alt="image" src="https://user-images.githubusercontent.com/2362647/129474421-e5f4fc51-d4db-4f65-a834-d2c622da859e.png">

first is All Players: None (clickable icon)
second is All Players: Limited (clickable icon)
third is All Players: Observer (not a clickable icon)
fourth is All Players: Owner (not a a clickable icon, and looks identical to 'Observer' icon)

**Comment by Malekal4699** [comment]
Reverted code, fixing this issue.
