### ISSUE TITLE
[Feature Request] Add option to allow 'Share with all' for limited Journal Entries

### ISSUE THREAD

**Issue by MarkeyMarke** [Malekal4699/fvtt-module-permission-viewer#18]
I like being able to simultaneously show journal entries and update permissions to observer:

![image](https://user-images.githubusercontent.com/32396474/135025186-b180da3f-8180-496c-bd79-e61fae0d804e.png)

This is useful for journal entries that set permissions to "All Players: None". However; when I try to click on journal entries set to "All Players: Limited", the dialogue prompt is skipped and I am only able to display the note to the players. Could we also provide this option to limited journal entries?

![image](https://user-images.githubusercontent.com/32396474/135025499-4c9e321d-1f94-4f2b-b697-aad7f47898b9.png)

![image](https://user-images.githubusercontent.com/32396474/135025528-07cfa971-a3fe-4989-948c-971f7eb5cfd1.png)

This is particularly useful if I want to have journal entries visible to players in a scene, but I also don't want them to see it in their journal entries until I show it to them.

**Comment by MarkeyMarke** [comment]
I realize that some users may not want this feature; so perhaps this could be a configurable option in module settings?

**Comment by Malekal4699** [comment]
Hi, I've disabled the bit of code that generated this specific case. 

If you want to try it out, you can get the source at the link below.

https://github.com/League-of-Foundry-Developers/fvtt-module-permission-viewer/archive/refs/heads/Malekal4699/issue9.zip

Thanks

**Comment by Malekal4699** [comment]
I've added the system setting and it now toggles the behavior.
Merging to 0.8.x
