### ISSUE TITLE
Icons are aligning vertically instead of horizontally

### ISSUE THREAD

**Issue by OutlandishVillainy** [Malekal4699/fvtt-module-permission-viewer#21]
The icons seem to be stacking on top of each other and overlapping instead of being a line.
![Untitled](https://user-images.githubusercontent.com/93902659/140707785-07ba6ee0-7a11-4976-bd87-8fe0113fe8ef.png)

**Comment by Malekal4699** [comment]
Hi,

can you try to add this

          div.permission-viewer > a {
          display:inline-flex;
     }

to modules/permission_viewer/styles/permission_viewer.css, save then refresh the page.

Let me know how it looks in you environment.

Thanks,
Marcel.

**Comment by Malekal4699** [comment]
.css should look like this:
![image](https://user-images.githubusercontent.com/78604153/142710271-72bb08b7-474d-4a3b-abe3-21a45d04078d.png)

**Comment by OutlandishVillainy** [comment]
Yep, that looks much better. Thanks!
![Untitled](https://user-images.githubusercontent.com/93902659/142710457-6c60024b-f05d-4f4d-aa98-ec5889980f95.png)

**Comment by Malekal4699** [comment]
If you get the latest css file from here, I also abs-middle centered the icons.

**Comment by Malekal4699** [comment]
Alright, closing this one.
