### ISSUE TITLE
Bug in release 0.8.11: Files are missing

### ISSUE THREAD

**Issue by brockhaus** [Malekal4699/fvtt-module-permission-viewer#22]
After installing 0.8.11 dialogues are missing translations.
Looking into the directory: images/ and lang/ is missing in that module folder. (Reproducable on my DEV system and my game-server)

I copied both folders manualy from repository, now i see text instead of placeholders.

**Comment by Malekal4699** [comment]
Ah I know why. Github workflow does not include that folder. I will correct this and regenerate the release.

**Comment by Malekal4699** [comment]
All set. Directory Accounted for and German Localization merged.

**Comment by brockhaus** [comment]
Cool, thanks! :)
