### ISSUE TITLE
[ENHANCEMENT] Localization Effort

### ISSUE THREAD

**Issue by Malekal4699** [Malekal4699/fvtt-module-permission-viewer#24]
Localization

**Comment by Malekal4699** [comment]
Hi Guys,

thanks for the Localization you added! I have added French and also some new strings. Aside from french, they have been added to the other languages, but remain in english.

So I've generated a branch for localization. If you have time, feel free to translate the new strings. Thanks!

@brockhaus @lozalojo

**Comment by brockhaus** [comment]
Will check the new entries shortly.
Can I sse how they result in interface I should. translate "blind" simply? :)

**Comment by lozalojo** [comment]
> So I've generated a branch for localization. If you have time, feel free to translate the new strings. Thanks!


done!

**Comment by Malekal4699** [comment]
Hey @brockhaus, currently look like this.
![image](https://user-images.githubusercontent.com/78604153/142745654-2cea5a7a-6fb4-4161-b7d5-8f0eb4fb85d3.png)

The other strings will likely never be seen as it's a shift in behavior with FVTT back in the days. 4 Releases ago! So it likely won't see light of day... but they were not translated so I stringed them anyway lol.

**Comment by brockhaus** [comment]
@Malekal4699 Well yes, the screen looks the same in my installation. :D 
So it is not really important to translate the "new" strings if they are not used anyways? ^^

**Comment by Malekal4699** [comment]
Likely not used. Could happen ;)

**Comment by Malekal4699** [comment]
Alright, I'll merge what's been done :)
