### ISSUE TITLE
v0.8.13 Error: You must provide a menu type that is FormApplication instance or subclass

### ISSUE THREAD

**Issue by thatlonelybugbear** [Malekal4699/fvtt-module-permission-viewer#28]
Upon loading Foundry 0.8.9

![image](https://user-images.githubusercontent.com/7237090/143033977-988e9abb-3cb2-444b-9338-574513431940.png)

**Comment by Malekal4699** [comment]
Hi,
this is fixed in the latest commit on github. Note that it's not breaking anything and the error will disappear in the next release.
Thank you for pointing it out.
M.
