### ISSUE TITLE
Center permission elements

### ISSUE THREAD

**Issue by Sky-Captain-13** [Malekal4699/fvtt-module-permission-viewer#3]
If you would, please add `vertical-align: middle;` to .permission-viewer-all, .permission-viewer-owner, .permission-viewer-user to center the indicators vertically.

![image](https://user-images.githubusercontent.com/10356477/102700084-3d4c7000-4218-11eb-8107-d59445fdb3be.png)

**Comment by Malekal4699** [comment]
> If you would, please add `vertical-align: middle;` to .permission-viewer-all, .permission-viewer-owner, .permission-viewer-user to center the indicators vertically.
> 
> ![image](https://user-images.githubusercontent.com/10356477/102700084-3d4c7000-4218-11eb-8107-d59445fdb3be.png)

Hi, I believe you are referring to the icons being a bit off vertical center here? 
![image](https://user-images.githubusercontent.com/78604153/107879088-cbee0e00-6ea4-11eb-91c1-5572642d4059.png)

**Comment by Malekal4699** [comment]
Tested under Chrome, Firefox and Edge. Likely KaKaRoTo fixed that and did not close this issue.
![image](https://user-images.githubusercontent.com/78604153/107896381-18b50180-6f04-11eb-9b21-40884f4644cc.png)
Closing issue.
