### ISSUE TITLE
Module Permisson Viewer not work with FoundryVTT V9

### ISSUE THREAD

**Issue by GenX187** [Malekal4699/fvtt-module-permission-viewer#31]
Bug @ FoundryVTT Version 9 Build 238:
Bug description: Module seem not to work with FoundryVTT V9

**Comment by Malekal4699** [comment]
Which branch are you using? Release 14 is still on 0.8.

As v9 is not officially out yet, you need to get the package from branch 0.9.x

**Comment by GenX187** [comment]
I am using "Permisson Viewer" - Version 0.8.14 

As you can read here: https://foundryvtt.com/releases/  
FoundryVTT releaeses V9 officially in Build 238 at December 20, 2021 (version numbering was changed).

**Comment by Malekal4699** [comment]
Yes. PV 0.8.14 is for lastest v8 of foundry.

Branch v0.9.x of PV is compatible with v9 of foundry.

Since v9 of foundry is still in test and not stable. Release of PV from site is matching current stable version of Foundry. Not test.
