### ISSUE TITLE
Exception thrown by permission_viewer on V9

### ISSUE THREAD

**Issue by StevenEvans1966** [Malekal4699/fvtt-module-permission-viewer#32]
When trying to show players art work Via ShowArtWork module I am getting this exception from permission_viewer

Uncaught (in promise) Error: This is not a registered game setting
[Detected 1 package: permission_viewer]
    at ClientSettings.get (foundry.js:2115)
    at JournalSheet._onShowPlayers (permission_viewer.js:134)

**Comment by Malekal4699** [comment]
Alright, go ahead and update. Should be clean now.
