### ISSUE TITLE
Allow .webm as audio file

### ISSUE THREAD

**Issue by Tupsi** [Malekal4699/fvtt-module-permission-viewer#33]
Please allow .webm files as well.

https://en.wikipedia.org/wiki/WebM

audio/webm is opus encoded inside a .webm container and works fine in modern browser which supports html5. Have no problem using these files in other parts of vtt, so it should just work the moment you allow .webm as well.

![image](https://user-images.githubusercontent.com/3730499/147406097-6b009bc0-8331-4b24-9282-cf9b40872761.png)

**Comment by Malekal4699** [comment]
Hi,

are we talking about permission viewer? Your screenshot refer to soundboard.

**Comment by Tupsi** [comment]
Oh my. I am sorry, but I landed on the wrong GitHub project. As you already figured, this request is for Soundboard.

I will close this.
