### ISSUE TITLE
Module.json is invalid

### ISSUE THREAD

**Issue by Vecna42** [Malekal4699/fvtt-module-permission-viewer#36]
Module version: 0.8.8
Foundry version: 0.8.9

![image](https://user-images.githubusercontent.com/12609554/149407651-cb446c6f-6fc5-4a9a-bcad-47c768f1b52e.png)

Attempting to install or update the module (version 0.8.8) returns the following error in Foundry:

`Installation failed: The request to https://github.com/League-of-Foundry-Developers/fvtt-module-permission-viewer/releases/0.8.8/download/module.json did not provide a valid manifest file`

![image](https://user-images.githubusercontent.com/12609554/149407675-51420967-9a95-4c7f-a836-933a422498ff.png)

Notes on steps followed: Module was installed to start with, attempted to upgrade, received the above error.  Uninstalled module, attempted to reinstall, got the same error.

**Comment by Malekal4699** [comment]
Hi,  

I did not account for v8 when I moved the repository. Let me see what I can do.

**Comment by Malekal4699** [comment]
Hi, I changed version 0.8.14 from v8 to point to the new repository. Please try again.

**Comment by Vecna42** [comment]
Hi - now I'm getting the slightly less helpful:

`k is not defined`.
![image](https://user-images.githubusercontent.com/12609554/149414464-e309d869-85aa-4234-b8b0-400f27f9f5c4.png)

I am using the link: `https://github.com/Malekal4699/fvtt-module-permission-viewer/releases/0.8.14/download/module.json` because the module is no longer showing in the module list.

![image](https://user-images.githubusercontent.com/12609554/149414610-555b6e1d-3bfa-4f65-bf84-8df0d193e36f.png)

**Comment by Malekal4699** [comment]
Once more with feelings?

**Comment by Malekal4699** [comment]
Alright I should have it now.

**Comment by Vecna42** [comment]
Yep - working now, thanks. :-)
