### ISSUE TITLE
PV - Feature Request - Add a visual indicator if a journal entry has text/image

### ISSUE THREAD

**Issue by fraserstanton** [Malekal4699/fvtt-module-permission-viewer#39]
**Is your feature request related to a problem? Please describe.**
It is not currently obvious with a journal entry if it has text and or an image, would be handy if there was an indicator if it had both (i.e. if you were looking at the image, it would show an indicator that there was text and vis versa.

**Describe the solution you'd like**
An indicator if it had both (i.e. if you were looking at the image, it would show an indicator that there was text and vis versa.

**Describe alternatives you've considered**
No alternatives considered atm.

**Additional context**
None

**Comment by Malekal4699** [comment]
Hi, that's actually somewhat out of scope for this module. 

This request would better be implemented in a Journal QOL module.

There even might be something out there already. 

Foundry's discord channel https://discord.gg/foundryvtt

#module-discussion


Thanks,

**Comment by fraserstanton** [comment]
np, no harm in asking right :)

**Comment by Malekal4699** [comment]
Indeed :)
