### ISSUE TITLE
Indicate user color for offline users

### ISSUE THREAD

**Issue by jessev14** [Malekal4699/fvtt-module-permission-viewer#4]
This may be out of the scope of this module but:
When preparing for a session as a GM (i.e. all other users are offline) the color of the permission indicators may not be helpful if you don't have player colors memorized. I would suggest adding a module setting that changes the outline color (or the color of some other element) for offline users in the bottom left Players window to match their player color.
It should be a straightforward CSS edit based on the quick mock up I did using the console (e.g. William's player is offline, Olwyn's player is online):

![image](https://user-images.githubusercontent.com/68755874/107910262-106ebd80-6f28-11eb-9ad4-b8d5e7dfecc6.png)

(enso#0361)

**Comment by Malekal4699** [comment]
Hi! I will check what's the default and current behavior. It might effectively be out of scope, but I'll check. I had an idea for some kind of mouse over tooltip, but haven't looked into that either yet.

Thanks, Malekal.

**Comment by Malekal4699** [comment]
Hi @jessev14 , please have a look at the development branch.
I've put in code to give more brightness to the inactive players icon.
https://github.com/League-of-Foundry-Developers/fvtt-module-permission-viewer/tree/development
![image](https://user-images.githubusercontent.com/78604153/108105743-000b2f80-705b-11eb-8744-1942f50a7c77.png)

**Comment by jessev14** [comment]
That looks great! The mouse over tooltip on the permission icons might be better, but either option should address the issue. Whatever is easier to implement gets my vote.

**Comment by Malekal4699** [comment]
Alright, I'll close this one. And add the tooltip to the the backlog/development.
Thank you for the suggestions. 

I will have the code reviewed and then push to prod.
