### ISSUE TITLE
Foundry 0.8 support

### ISSUE THREAD

**Issue by Sk1mble** [Malekal4699/fvtt-module-permission-viewer#7]
Permission Viewer is working well in Foundry 0.8 except one small issue; the syntax has changed from game.users.entries to game.users.contents. 

Line 172 of permission-viewer therefore needs to be changed to:

![image](https://user-images.githubusercontent.com/1439478/108616668-6e5b4380-7407-11eb-9046-7b30b668697d.png)

**Comment by Sk1mble** [comment]
Also, this is not a breaking issue, but ._id is being deprecated so this line would need to change also:

![image](https://user-images.githubusercontent.com/1439478/108616697-c3975500-7407-11eb-9da7-a6a175d4af0c.png)

**Comment by Malekal4699** [comment]
Hi, this was corrected/changed on the day of the release and sent to Development branch. I will create a new branch specific to 0.8.0.

Thanks, Malekal
