### ISSUE TITLE
Allow "showing" only to designated players for Actors and Items as well

### ISSUE THREAD

**Issue by MacBad1** [Malekal4699/fvtt-module-permission-viewer#9]
The pop-up that appears when you try to "show players" something from the Journal and allows you to either "send to all" or "send to list", could also be used when trying to "show players" something from the Actors and Items categories.
There are many times when one could need to show an Actor portrait only to specific players and this could really help with that.

If it wouldn't be too much trouble, I'd love such a feature, thank you in advance!

**Comment by Malekal4699** [comment]
Is that part of the mod? I'll have to check that...

**Comment by MacBad1** [comment]
@Malekal4699 
I was told on the Foundry discord that it is indeed part of the mod.

**Comment by Malekal4699** [comment]
Well I'll have a look!

**Comment by Malekal4699** [comment]
Hi,

branch here has the code for this case disabled. Want to try it out?

https://github.com/League-of-Foundry-Developers/fvtt-module-permission-viewer/archive/refs/heads/Malekal4699/issue9.zip

Thanks. M.

**Comment by Malekal4699** [comment]
Wrong Issue...
